/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define ADC_BASE_ADDR         0x58026000UL
#define ADC_CR1_REG_OFFSET    0x08UL
#define ADC_CR1_REG_ADDR      (ADC_BASE_ADDR +ADC_CR1_REG_OFFSET )
#define RCC_BASE_ADDR         0x58024400UL
#define RCC_APB4_EN_OFFSET    0x0E0UL
#define RCC_APB4_ENR_ADDR     (RCC_BASE_ADDR+RCC_APB4_EN_OFFSET)


int main(void)
{
    /* Loop forever */

	uint32_t  *pAdcCrlReg = (uint32_t*) ADC_CR1_REG_ADDR;
	uint32_t *pRccApb4Enr=(uint32_t*)RCC_APB4_ENR_ADDR;

	*pRccApb4Enr |=(1<<24);
	*pAdcCrlReg |= (1 << 0);
	for(;;);
}
