/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDR         0x58024400UL
#define RCC_CFGR_REG_OFFSET       0x010UL
#define RCC_CFGR_REG_ADDR    (RCC_BASE_ADDR+RCC_CFGR_REG_OFFSET)

#define GPIOA_BASE_ADDR       0x58020000UL


int main(void)
{
   //1. Configure the RCC_CFGR MCO1 bit fields to select HSI as clock source
   uint32_t *pRccCfgrReg=(uint32_t*)RCC_CFGR_REG_ADDR;
   *pRccCfgrReg &=~(0x7<<22);

	//a ) Enable the peripheral clock for GPIOA peripheral
   uint32_t *pGPIOAModeReg = (uint32_t*)(RCC_BASE_ADDR + 0x0E0);
   *pGPIOAModeReg |=(1<<0);

   /* 3️⃣ Set MCO1 prescaler to /4 (bits 27:24 = 0100) */
   //uint32_t *pRccCfgrReg = (uint32_t*)RCC_CFGR_REG_ADDR;  // pointer to RCC_CFGR
   *pRccCfgrReg &= ~(0xF << 18);  // clear bits 21:18
   *pRccCfgrReg |=  (0x4 << 18);  // set prescaler to /4

   //b ) Configure the mode of GPIOA pin 8 as alternate function mode
   uint32_t *pGPIOAModeReg2=(uint32_t*)(GPIOA_BASE_ADDR+00);
   *pGPIOAModeReg2 &= ~( 0x3 << 16); //clear
   *pGPIOAModeReg2 |= ( 0x2 << 16);  //set#

   uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
   	*pGPIOAAltFunHighReg &= ~( 0xf << 0);


	for(;;);
}
